apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app.fullname.prefect-deploy" . }}
spec:
  replicas: {{ .Values.services.workflows.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ include "web-app.fullname.prefect-deploy" . }}
  template:
    metadata:
      labels:
        app: {{ include "web-app.fullname.prefect-deploy" . }}
    spec:
      serviceAccountName: deployer
      containers:
        - name: prefect-deploy
          image: "{{ .Values.registry }}/{{ .Values.services.workflows.deploy.image.stream }}:{{ .Values.services.workflows.deploy.image.tag }}"
          args:
            - "prefect"
            - "deploy"
            - "start"
            - "--pool"
            - "{{ .Values.services.workflows.deploy.queue }}"
          ports:
            - containerPort: 4201
          env:
            - name: PREFECT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "web-app.fullname" . }}-config
                  key: PREFECT_API_URL

            - name: ZARR_STORE_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "web-app.fullname" . }}-config
                  key: ZARR_STORE_PATH

          resources:
            {{- toYaml .Values.services.workflows.deploy.resources | nindent 12 }}
