{{- $ps := index .Values "prefect-server" }}

{{- if $ps.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "conservation-tool.fullname.prefect-server" . }}
  labels:
    app: {{ include "conservation-tool.fullname.prefect-server" . }}
spec:
  {{- if $ps.route.host }}
  host: {{ $ps.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "conservation-tool.fullname.prefect-server" . }}
  port:
    targetPort: {{ .Values.ports.prefect_server_api | default 4200 }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}