{{- $root := . -}}
{{- range $profileName, $profile := .Values.services.workflows.worker.profiles }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conservation-tool.fullname.prefect-worker" $root }}-{{ $profileName }}
  labels:
    {{- include "conservation-tool.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.services.workflows.worker.service.type }}
  selector:
    app: {{ include "conservation-tool.fullname.prefect-worker" $root }}-{{ $profileName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $root.Values.services.workflows.worker.service.port }}
      targetPort: {{ $root.Values.services.workflows.worker.service.targetPort }}
---
{{- end }}
