apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conservation-tool.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: '{{ .Values.env.NODE_ENV | default "development" }}'
  CHANGE_VERSION: '{{ .Values.environment.changeId | default "" }}'
  VERSION: '{{ .Chart.AppVersion | default "" }}'
  API_HOST: '{{ .Values.env.FRONTEND_API_HOST | default "" }}'
  APP_NODE_ENV: '{{ .Values.env.NODE_ENV | default "development" }}'
  SITEMINDER_LOGOUT_URL: '{{ .Values.env.VITE_APP_SITEMINDER_LOGOUT_URL | default "" }}'
  MAX_UPLOAD_NUM_FILES: '{{ .Values.env.VITE_APP_MAX_UPLOAD_NUM_FILES | default "10" }}'
  MAX_UPLOAD_FILE_SIZE: '{{ .Values.env.VITE_APP_MAX_UPLOAD_FILE_SIZE | default "52428800" }}'
  BACKBONE_PUBLIC_API_HOST: '{{ .Values.env.VITE_APP_BACKBONE_PUBLIC_API_HOST | default "" }}'
  BIOHUB_TAXON_PATH: '{{ .Values.env.VITE_APP_BIOHUB_TAXON_PATH | default "" }}'
  BIOHUB_TAXON_TSN_PATH: '{{ .Values.env.VITE_APP_BIOHUB_TAXON_TSN_PATH | default "" }}'
  FEATURE_FLAGS: '{{ .Values.env.VITE_APP_FEATURE_FLAGS | default "" }}'
