apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - delete
      - patch

  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["batch"]
    resources:
      - jobs/status
    verbs:
      - get
      - patch
      - update

  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: prefect-server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: prefect-server
  apiGroup: rbac.authorization.k8s.io