apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: '{{ include "web-app.fullname.frontend" . }}-ingress'
spec:
  podSelector:
    matchLabels:
      app: {{ include "web-app.fullname.frontend" . }}
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from OpenShift router
    - from:
        - namespaceSelector:
            matchLabels:
              name: openshift-ingress
      ports:
        - protocol: TCP
          port: {{ .Values.services.frontend.service.targetPort }}
    
    # Allow traffic from same namespace (for service-to-service communication)
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.services.frontend.service.targetPort }}