import { z } from 'zod';

/**
 * Profile model representing core fields of a profile.
 */
export const Profile = z.object({
  profile_id: z.string().uuid(), // UUID type for profile_id
  identity_source: z.string(), // Identity source as string (e.g., 'SYSTEM', 'IDIR', 'DATABASE')
  profile_identifier: z.string().max(200), // Max length of 200 for profile_identifier
  profile_guid: z.string().max(200), // Max length of 200 for profile_guid
  role_id: z.string().uuid().optional(), // Optional role_id
  role_name: z.string().max(100).optional(), // Optional role_name (max length 100)
  agency: z.string().max(200).nullable().optional()
});

export type Profile = z.infer<typeof Profile>;

/** Type for creating a new profile */
export const CreateProfile = Profile.omit({
  profile_id: true // profile_id is generated by the database
});

export type CreateProfile = z.infer<typeof CreateProfile>;

/** Type for updating an existing profile */
export const UpdateProfile = Profile.partial().omit({
  profile_id: true // profile_id is not needed for update
});

export type UpdateProfile = z.infer<typeof UpdateProfile>;

/** Type for deleting a profile */
export const DeleteProfile = z.object({
  profile_id: z.string().uuid() // Only profile_id is needed for deletion
});

export type DeleteProfile = z.infer<typeof DeleteProfile>;

/** Profile with extended fields for Keycloak integration */
export const ProfileKeycloak = Profile.extend({
  display_name: z.string().nullable(),
  given_name: z.string().nullable(),
  family_name: z.string().nullable(),
  email: z.string().nullable(),
  agency: z.string().nullable(),
  notes: z.string().nullable()
});

export type ProfileKeycloak = z.infer<typeof ProfileKeycloak>;

/** Type for upserting a profile (with profile_id omitted) */
export const UpsertProfile = ProfileKeycloak.omit({
  profile_id: true
});

export type UpsertProfile = z.infer<typeof UpsertProfile>;
