apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-server
  namespace: fa9440-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-server
  namespace: fa9440-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-server
  namespace: fa9440-dev
subjects:
  - kind: ServiceAccount
    name: prefect-server
    namespace: fa9440-dev
roleRef:
  kind: Role
  name: prefect-server
  apiGroup: rbac.authorization.k8s.io
