import { Knex } from 'knex';

const DB_SCHEMA = process.env.DB_SCHEMA!;
const DB_USER_API = process.env.DB_USER_API!;
const DB_USER_API_PASS = process.env.DB_USER_API_PASS!;
const DB_USER_PREFECT = process.env.DB_USER_PREFECT!;
const DB_USER_PREFECT_PASS = process.env.DB_USER_PREFECT_PASS!;
const DB_DATABASE = process.env.DB_DATABASE!;

const DB_SCHEMA_PREFECT = 'prefect';

export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE SCHEMA ${DB_SCHEMA};
    CREATE SCHEMA ${DB_SCHEMA_PREFECT};
    
    GRANT ALL ON SCHEMA ${DB_SCHEMA} TO postgres;
    GRANT ALL ON SCHEMA ${DB_SCHEMA_PREFECT} TO postgres;

    CREATE USER "${DB_USER_API}" WITH PASSWORD '${DB_USER_API_PASS}';
    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO "${DB_USER_API}";
    ALTER ROLE "${DB_USER_API}" SET search_path TO "\\$user", ${DB_SCHEMA}, public;

    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${DB_USER_API}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
      GRANT EXECUTE ON FUNCTIONS TO "${DB_USER_API}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
      GRANT USAGE ON TYPES TO "${DB_USER_API}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
      GRANT USAGE, SELECT ON SEQUENCES TO "${DB_USER_API}";

    CREATE USER "${DB_USER_PREFECT}" WITH PASSWORD '${DB_USER_PREFECT_PASS}';
    GRANT USAGE, CREATE ON SCHEMA ${DB_SCHEMA_PREFECT} TO "${DB_USER_PREFECT}";
    ALTER ROLE "${DB_USER_PREFECT}" SET search_path TO "\\$user", ${DB_SCHEMA_PREFECT}, public;

    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA_PREFECT}
      GRANT ALL PRIVILEGES ON TABLES TO "${DB_USER_PREFECT}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA_PREFECT}
      GRANT ALL PRIVILEGES ON SEQUENCES TO "${DB_USER_PREFECT}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA_PREFECT}
      GRANT EXECUTE ON FUNCTIONS TO "${DB_USER_PREFECT}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA_PREFECT}
      GRANT USAGE ON TYPES TO "${DB_USER_PREFECT}";

    -- Grant the Prefect user the ability to create extensions
    GRANT CREATE ON DATABASE ${DB_DATABASE} TO "${DB_USER_PREFECT}";

    -- Grant usage on the pg_catalog schema (this is necessary for some system objects like extensions)
    GRANT USAGE ON SCHEMA pg_catalog TO "${DB_USER_PREFECT}";

    SET ROLE postgres;
    SET search_path = ${DB_SCHEMA}, public;
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`
    DROP SCHEMA IF EXISTS ${DB_SCHEMA} CASCADE;
    DROP SCHEMA IF EXISTS ${DB_SCHEMA_PREFECT} CASCADE;
    DROP USER IF EXISTS "${DB_USER_API}";
    DROP USER IF EXISTS "${DB_USER_PREFECT}";
  `);
}
