environment:
  id: "prod"
  name: "prod"

prefect-server:
  ingress:
    host:
      hostname: "conservation-tool-prefect-server-fa9440-prod.apps.gold.devops.gov.bc.ca"

services:
  frontend:
    image:
      tag: "prod"
    config:
      image:
        tag: "prod"
  workflows:
    worker:
      replicas: 1
      image:
        tag: "prod"
    deploy:
      replicas: 1
      image:
        tag: "prod"
  api:
    image:
      tag: "prod"
    route:
      host: "conservation-tool-api-fa9440-prod.apps.gold.devops.gov.bc.ca"
  db:
    image:
      stream: "postgres"
      tag: "17-alpine"
  dbSetup:
    image:
      tag: "prod"

env:
  NODE_ENV: "production"
  FRONTEND_API_HOST: "https://conservation-tool-api-fa9440-prod.apps.gold.devops.gov.bc.ca"
