services:
  frontend:
    image:
      tag: dev
    env:
      environment: dev

  workflows:
    server:
      image:
        tag: dev
    worker:
      image:
        tag: dev
    env:
      environment: dev
