services:
  frontend:
    image:
      tag: test
    env:
      environment: test

  workflows:
    server:
      image:
        tag: test
    worker:
      image:
        tag: test
    deploy:
      image:
        tag: test
    env:
      environment: test
