env:
  NODE_ENV: "production"
  PREFECT_API_URL: "http://prefect-server.fa9440-prod.svc.cluster.local:4200/api"
  
  services:
  frontend:
    image:
      tag: prod
    env:
      environment: prod

  workflows:
    server:
      image:
        tag: prod
    worker:
      image:
        tag: prod
    deploy:
      image:
        tag: prod
    env:
      environment: prod
