environment:
  id: "test"
  name: "test"

prefect-server:
  ingress:
    host:
      hostname: "conservation-tool-prefect-server-fa9440-test.apps.gold.devops.gov.bc.ca"

services:
  frontend:
    image:
      tag: "test"
    config:
      image:
        tag: "test"
  workflows:
    worker:
      image:
        tag: "test"
    deploy:
      image:
        tag: "test"
  api:
    image:
      tag: "test"
    route:
      host: "conservation-tool-api-fa9440-test.apps.gold.devops.gov.bc.ca"
  db:
    image:
      stream: "postgres"
      tag: "17-alpine"
  dbSetup:
    image:
      tag: "test"

env:
  NODE_ENV: "test"
  FRONTEND_API_HOST: "https://conservation-tool-api-fa9440-test.apps.gold.devops.gov.bc.ca"
