environment:
  id: "prod"
  name: "prod"

prefect-server:
  ingress:
    host:
      hostname: "conservation-tool-prefect-server-fa9440-prod.apps.gold.devops.gov.bc.ca"

  ui:
    podSecurityContext:
      runAsUser: 1003590000
      fsGroup: null
    containerSecurityContext:
      runAsUser: 1003590000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

  server:
    uiConfig:
      prefectUiApiUrl: "https://conservation-tool-prefect-server-fa9440-prod.apps.gold.devops.gov.bc.ca/api"
    podSecurityContext:
      runAsUser: 1003590000
      fsGroup: null
    containerSecurityContext:
      runAsUser: 1003590000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

  migrations:
    securityContext:
      runAsUser: 1003590000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities: {}

database:
  postgresql:
    primary:
      podSecurityContext:
        runAsUser: 1003590000
        fsGroup: 1003590000
      containerSecurityContext:
        runAsUser: 1003590000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL

services:
  frontend:
    image:
      tag: "prod"
    config:
      image:
        tag: "prod"
    securityContext:
      runAsUser: 1003590000
      fsGroup: 1003590000

  workflows:
    worker:
      image:
        tag: "prod"
      securityContext:
        runAsUser: 1003590000

    deploy:
      image:
        tag: "prod"
      securityContext:
        runAsUser: 1003590000

  api:
    image:
      tag: "prod"
    route:
      host: "conservation-tool-api-fa9440-prod.apps.gold.devops.gov.bc.ca"
    securityContext:
      runAsUser: 1003590000
      fsGroup: 1003590000

  db:
    image:
      tag: "prod"
    securityContext:
      runAsUser: 1003590000
      fsGroup: 1003590000

  dbSetup:
    image:
      tag: "prod"

backgroundServices:
  podSecurityContext:
    runAsUser: 1003590000
    fsGroup: 1003590000
  containerSecurityContext:
    runAsUser: 1003590000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

env:
  NODE_ENV: "production"
  FRONTEND_API_HOST: "https://conservation-tool-api-fa9440-prod.apps.gold.devops.gov.bc.ca"
