env:
  NODE_ENV: "test"
  PREFECT_API_URL: "http://prefect-server.fa9440-test.svc.cluster.local:4200/api"
  ZARR_STORE_PATH: "/data/output_1000.zarr"

services:
  frontend:
    image:
      tag: test

  workflows:
    worker:
      image:
        tag: test
      env:

    deploy:
      image:
        tag: test
