name: Promote to Test

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Confirm deployment"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      source_tag: dev
      target_tag: test
      environment: test
