apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conservation-tool.fullname.api" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.api.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "conservation-tool.fullname.api" . }}
  template:
    metadata:
      labels:
        app: {{ include "conservation-tool.fullname.api" . }}
      annotations:
        conservation-tool/release-revision: {{ .Release.Revision | quote }}
    spec:
      serviceAccountName: {{ .Values.services.api.serviceAccountName | default "deployer" }}
      securityContext:
        runAsNonRoot: true
        {{- if .Values.services.api.securityContext.runAsUser }}
        runAsUser: {{ .Values.services.api.securityContext.runAsUser }}
        {{- end }}
        {{- if .Values.services.api.securityContext.fsGroup }}
        fsGroup: {{ .Values.services.api.securityContext.fsGroup }}
        {{- end }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: "{{ .Values.registry }}/{{ .Values.services.api.image.stream }}:{{ .Values.services.api.image.tag }}"
          imagePullPolicy: {{ .Values.services.api.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.ports.api }}
          securityContext:
            runAsNonRoot: true
            {{- if .Values.services.api.securityContext.runAsUser }}
            runAsUser: {{ .Values.services.api.securityContext.runAsUser }}
            {{- end }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: NODE_OPTIONS
              value: {{ .Values.env.NODE_OPTIONS | quote }}
            - name: API_HOST
              value: {{ .Values.env.API_HOST | quote }}
            - name: API_PORT
              value: {{ .Values.env.API_PORT | quote }}
            - name: APP_HOST
              value: {{ .Values.env.APP_HOST | quote }} # need to set this to not an empty string
            - name: ZARR_STORE_PATH
              value: {{ .Values.env.ZARR_STORE_PATH | quote }}
            - name: DB_HOST
              value: {{ include "conservation-tool.fullname.db" . | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_DATABASE
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_SCHEMA
            - name: DB_USER_API
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_USER_API
            - name: DB_USER_API_PASS
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_USER_API_PASS
            - name: DB_USER_PREFECT
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_USER_PREFECT
            - name: DB_USER_PREFECT_PASS
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_USER_PREFECT_PASS
            - name: DB_ADMIN
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_ADMIN
            - name: DB_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-db
                  key: DB_ADMIN_PASS
            - name: DB_POOL_SIZE
              value: {{ .Values.env.DB_POOL_SIZE | quote }}
            - name: DB_CONNECTION_MAX_USES
              value: {{ .Values.env.DB_CONNECTION_MAX_USES | quote }}
            - name: DB_CONNECTION_TIMEOUT
              value: {{ .Values.env.DB_CONNECTION_TIMEOUT | quote }}
            - name: DB_IDLE_TIMEOUT
              value: {{ .Values.env.DB_IDLE_TIMEOUT | quote }}
            - name: KEYCLOAK_HOST
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_HOST
              # value: {{ .Values.env.KEYCLOAK_HOST | quote }}
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_REALM
              # value: {{ .Values.env.KEYCLOAK_REALM | quote }}
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_ADMIN_USERNAME
              # value: {{ .Values.env.KEYCLOAK_ADMIN_USERNAME | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
              # value: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD | quote }}
            - name: KEYCLOAK_API_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_API_TOKEN_URL
              # value: {{ .Values.env.KEYCLOAK_API_TOKEN_URL | quote }}
            - name: KEYCLOAK_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_API_CLIENT_ID
              # value: {{ .Values.env.KEYCLOAK_API_CLIENT_ID | quote }}
            - name: KEYCLOAK_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_API_CLIENT_SECRET
              # value: {{ .Values.env.KEYCLOAK_API_CLIENT_SECRET | quote }}
            - name: KEYCLOAK_API_HOST
              # value: {{ .Values.env.KEYCLOAK_API_HOST | quote }}
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_API_HOST
            - name: KEYCLOAK_API_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-keycloak
                  key: KEYCLOAK_API_ENVIRONMENT
              # value: {{ .Values.env.KEYCLOAK_API_ENVIRONMENT | quote }}
            - name: OBJECT_STORE_URL
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-object-storage
                  key: OBJECT_STORE_URL
              # value: {{ .Values.env.OBJECT_STORE_URL | quote }}
            - name: OBJECT_STORE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-object-storage
                  key: OBJECT_STORE_ACCESS_KEY_ID
              # value: {{ .Values.env.OBJECT_STORE_ACCESS_KEY_ID | quote }}
            - name: OBJECT_STORE_SECRET_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-object-storage
                  key: OBJECT_STORE_SECRET_KEY_ID
              # value: {{ .Values.env.OBJECT_STORE_SECRET_KEY_ID | quote }}
            - name: OBJECT_STORE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-object-storage
                  key: OBJECT_STORE_BUCKET_NAME
              # value: {{ .Values.env.OBJECT_STORE_BUCKET_NAME | quote }}
            - name: S3_KEY_PREFIX
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-object-storage
                  key: S3_KEY_PREFIX
              # value: {{ .Values.env.S3_KEY_PREFIX | quote }}
            - name: PREFECT_API_URL
              value: {{ .Values.env.PREFECT_API_URL | quote }}
            - name: PREFECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-api
                  key: PREFECT_API_KEY
                  optional: true
            - name: CONSERVATION_API_URL
              value: {{ .Values.env.CONSERVATION_API_URL | quote }} # optional
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: conservation-tool-api
                  key: INTERNAL_API_KEY
              # value: {{ .Values.env.INTERNAL_API_KEY | quote }}
            {{- if .Values.services.api.env }}
            {{- toYaml .Values.services.api.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.services.api.resources | nindent 12 }}
